version: '3.7'

services:

  car.ajp:
    container_name: car.ajp
    image: ghcr.io/qtc-de/container-arsenal/ajp:1.0.0
    build: .
    environment:
      TARGET_HOST: ${car_target_host}
      TARGET_PORT: ${car_target_port}
      LISTEN_PORT: ${car_http_port}
      LOCAL_UID: ${car_local_uid}
    volumes:
      - ${car_log_folder}:/var/log/apache2
      - ./config/httpd_raw.conf:/etc/apache2/httpd_raw.conf
      - ./config/ajp.conf:/etc/apache2/ajp.conf
      - ./config/jk_workers.properties:/etc/apache2/jk_workers.properties
      - ./scripts/start.sh:/scripts/start.sh
    network_mode: "host"
