version: '3.7'

services:

  car.ajp:
    container_name: car.ajp
    build: .
    image: car/ajp
    environment:
      HOST: ${car_target_host}
      PORT: ${car_target_port}
    volumes:
      - ${car_log_folder}:/usr/local/apache2/logs/
      - ./config/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./config/ajp.conf:/usr/local/apache2/conf/extra/ajp.conf
      - ./config/jk_workers.properties:/usr/local/apache2/conf/extra/jk_workers.properties
      - ./scripts/start.sh:/scripts/start.sh
    ports:
      - "127.0.0.1:${car_http_port}:80"
