version: '3.7'

services:

  car.ftp:
    container_name: car.ftp
    image: car/ftp
    build: .
    volumes:
      - ${car_user_folder}:/ftp/user
      - ${car_anon_folder}:/ftp/anon
      - ./scripts/start.sh:/scripts/start.sh
      - ./config/vsftpd.conf:/etc/vsftpd/vsftpd.conf
    ports:
      - "${car_ftp_port}:21"
